### ISSUE TITLE
return ft: notarealcommand: command not found...

### ISSUE THREAD

**Issue by Jmainguy** [AVGP/fake-terminal#4]
Really love this project, working with it on my personal website today. I would love if it returned command not found like bash does if the command is not defined.

bash: notarealcommand: command not found...

**Comment by AVGP** [comment]
Lovely idea! 

If you're interested in implementing this and make a pull request for this repository, go for it!

I guess you'd have to check if the given command does not exist in `self.commands` and then print your message.

The piece of code that checks if an entered command is supported is in https://github.com/AVGP/fake-terminal/blob/gh-pages/fake-terminal.html#L122 - so you'd need an "else if" for it.

**Comment by Jmainguy** [comment]
@AVGP Thank you for pointing me in the right direction, I could not figure out how to just print a string to the terminal, so I wrote a quick new function for it, if there is a better way please let me know. Checkout the PR #5

**Comment by Jmainguy** [comment]
Going thru my open issues and came across this. Going to close this out.
